export const MAIL_LIST_REQUEST      = 'MAIL_LIST_REQUEST'
export const MAIL_LIST_RESULT       = 'MAIL_LIST_RESULT'
export const MAIL_SEND_REQUEST      = 'MAIL_SEND_REQUEST'
export const MAIL_SEND_RESULT       = 'MAIL_SEND_RESULT'